# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slate < Formula
  desc ""
  homepage "https://github.com/kanennn/slate"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Darwin_x86_64.tar.gz"
      sha256 "c8f5fd67ec9ac0fb7f0cf176d26595c07bb859ad8427b0e312f720b5885806cd"

      def install
        bin.install "slate"
      end
    end
    on_arm do
      url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Darwin_arm64.tar.gz"
      sha256 "9b36de500727efe616630735e2f8d9483ca7272dd8258ad48653ec9c7d86c5a6"

      def install
        bin.install "slate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Linux_x86_64.tar.gz"
        sha256 "365b5ef47a075a377fe929953907434302b5fe0c1528d1347a9b9d412eca66e9"

        def install
          bin.install "slate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Linux_arm64.tar.gz"
        sha256 "a4947081a320ceab0e39c3caf3b9f14d63ee9d577d85a430bebf45475157f839"

        def install
          bin.install "slate"
        end
      end
    end
  end
end
