# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slate < Formula
  desc ""
  homepage "https://github.com/kanennn/slate"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Darwin_x86_64.tar.gz"
      sha256 "33ddad9afffce5ff49a91d248c97937c0faa6995787c3a60ee923f8f135e96bc"

      def install
        bin.install "slate"
      end
    end
    on_arm do
      url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Darwin_arm64.tar.gz"
      sha256 "c5ed8d8803b12a15e82110c8585346ae64a10819dd5d2d0712d746d695c0c9f1"

      def install
        bin.install "slate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Linux_x86_64.tar.gz"
        sha256 "aff96f960cc5d1cd876d00e888a2d3ddf74415c5f835870be7411c29d21f12e0"

        def install
          bin.install "slate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kanennn/slate/releases/download/v1.0.0/slate_Linux_arm64.tar.gz"
        sha256 "646f897b15cca16e58fef663b58e431d7c9721cb447f3599caf1d174454ea521"

        def install
          bin.install "slate"
        end
      end
    end
  end
end
